# Generated by Django 5.0.6 on 2024-06-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
                ('paso_numero', models.IntegerField()),
                ('paso_titulo', models.CharField(max_length=50)),
                ('paso_nombre', models.CharField(max_length=50)),
                ('paso_descripcion', models.CharField(max_length=1000)),
                ('paso_image', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Jardines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Plantas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
            ],
        ),
    ]
