# Generated by Django 5.0.6 on 2024-07-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('mensaje', models.CharField(max_length=240)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cultivos',
            options={'verbose_name': 'Cultivos', 'verbose_name_plural': 'Cultivos'},
        ),
        migrations.AlterModelOptions(
            name='jardines',
            options={'verbose_name': 'Jardines', 'verbose_name_plural': 'Jardines'},
        ),
        migrations.AlterModelOptions(
            name='plantas',
            options={'verbose_name': 'Plantas', 'verbose_name_plural': 'Plantas'},
        ),
    ]
