# Generated by Django 5.0.6 on 2024-07-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_contactos_alter_cultivos_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactos',
            options={'verbose_name': 'Contactos', 'verbose_name_plural': 'Contactos'},
        ),
        migrations.AlterField(
            model_name='contactos',
            name='mensaje',
            field=models.TextField(max_length=500),
        ),
    ]
