# Generated by Django 5.0.6 on 2024-07-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_alter_contactos_options_alter_contactos_mensaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReproducciónRosales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paso_numero', models.IntegerField()),
                ('paso_nombre', models.CharField(max_length=50)),
                ('paso_descripcion', models.CharField(max_length=1000)),
                ('paso_image', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='cultivos',
            name='paso_descripcion',
        ),
        migrations.RemoveField(
            model_name='cultivos',
            name='paso_image',
        ),
        migrations.RemoveField(
            model_name='cultivos',
            name='paso_nombre',
        ),
        migrations.RemoveField(
            model_name='cultivos',
            name='paso_numero',
        ),
        migrations.RemoveField(
            model_name='cultivos',
            name='paso_titulo',
        ),
    ]
