# Generated by Django 5.0.6 on 2024-07-15 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_reproducciónrosales_remove_cultivos_paso_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReproducciónRosales',
            new_name='ReprRosales',
        ),
    ]
