# Generated by Django 5.0.6 on 2024-07-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_rename_reproducciónrosales_reprrosales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reproduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('paso_numero', models.IntegerField()),
                ('paso_nombre', models.CharField(max_length=50)),
                ('paso_descripcion', models.CharField(max_length=1000)),
                ('paso_image', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Reproducción de rosales',
                'verbose_name_plural': 'Reproducción de rosales',
                'ordering': ['nombre', 'paso_numero'],
            },
        ),
        migrations.DeleteModel(
            name='ReprRosales',
        ),
    ]
